
################################### Cluster ###################################

cluster:
  name: atlasd
  hosts: ["192.168.2.1", "192.168.2.5"]
  cookie: "SecretCookie"

#################################### Node #####################################

node:
  master: true
  worker: false

#################################### Paths ####################################

path:
# Path to directory containing configuration (this file and logging.yml):
  conf: /apps/atlasd/etc/

# Path to data files
  data: /tmp/atlasd

# Path to temporary files:
  work: /tmp

# Path to log files:
  logs: /var/log/atlasd

############################## Network And HTTP ###############################

# internal communication port
inet:
  host: 192.168.2.5
  port: 9100

http:
# Disable HTTP completely:
  enabled: true

# Set both 'bind_host' and 'publish_host':
  host: 0.0.0.0

# Set a custom port to listen for HTTP traffic:
  port: 9900

############################## Monitors ###############################

monitors:
  os:
    mem_watermark: 80

  #rabbitmq:
  #  mode: api
  #  host: "192.168.2.5"
  #  user: guest
  #  pass: guest
  #
  #  monitors:
  #    task-listen-low:
  #      exchange: parsley
  #      queue: "ds.conveyer.task.low"
  #
  #    task-listen-middle:
  #      exchange: parsley
  #      queue: "ds.conveyer.task.middle"
  #
  #    task-listen-high:
  #      exchange: parsley
  #      queue: "ds.conveyer.task.high"
